{% set python_min = "3.9.0" %}
{% set name = "fractal-tasks-core" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractal_tasks_core-{{ version }}.tar.gz
  sha256: 354c2e9bfe0e784bc18003d6437639aabb6803ca19a9202c79af56f9fd979be6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - dask-core >=2023.1.0
    - fsspec !=2023.9.0
    - zarr >=2.13.6,<3
    - numpy <=2.1.0
    - pandas >=1.2.0
    - lxml >=4.9.1,<5.0.0
    - pydantic >2,<=2.8.2
    - docstring_parser >=0.15.0,<0.16.0
    - anndata >=0.8.0,<0.11.0
    - filelock 3.13.*
  run_constrained:
    - Pillow >=9.1.1
    - imageio-ffmpeg >=0.4.7,<0.5.0
    - scikit-image >=0.19
    - napari-segment-blobs-and-things-with-membranes >=0.3.3,<0.4.0
    - napari-workflows >=0.2.8,<0.3.0
    - stackview <0.9.0
    - napari-skimage-regionprops >=0.8.1,<0.9.0
    - napari-tools-menu >=0.1.19,<0.2.0
    - cellpose >=2.2.0,<2.3.0
    - pytorch <=3.0.0
    - image_registration >=0.2.9

test:
  imports:
    - fractal_tasks_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/fractal-tasks-core
  summary: Core bioimage-analysis library and tasks of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jluethi
    - mfranzon
    - tcompa
